using PecuarioProPlatform.API.BusinessAdministration.Domain.Model.Entities;

namespace PecuarioProPlatform.API.BusinessAdministration.Domain.Model.Queries;

public record GetBovineByBovineIdentifierQuery(BovineIdentifier BovineIdentifier);